[package]
name = "exo-identity"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
exo-core.workspace = true
serde.workspace = true
thiserror.workspace = true
ed25519-dalek.workspace = true
serde_cbor.workspace = true
blake3.workspace = true
bs58.workspace = true

[dev-dependencies]
proptest.workspace = true
rand.workspace = true
ed25519-dalek = { workspace = true, features = ["rand_core"] }
